### ISSUE TITLE
No injury bug and not being able to use items with VIDEO INCLUDED

### ISSUE THREAD

**Issue by Jameslott12345678900** [ND-Framework/ND_Ambulance#1]
when trying to use badages or Guze, it does not let you after being injured, so it leads to death without you being able to do anything Also, after death, there is no way to respawn
here is a short video of whats going on ---> https://streamable.com/6hoay7
med kit works, but it dose not stop bleeding and there is no way for me to stop it if i have no injuries.

**Comment by Willow-6855** [comment]
does it say anything in the f8 console and the server console?

**Comment by Andyyy7666** [comment]
should be good now
